### DISCUSSION TITLE
v0.1.2

### DISCUSSION THREAD

**Discussion by Nicxe** [Nicxe/f1_sensor#7] [Announcements]
### New Sensors
- `sensor.f1_latest_race_results`:  
  Displays detailed results from the most recent Formula 1 race.
  
- `sensor.f1_season_results`:  
  Contains a full array of race results for the ongoing season.

---

### How to Enable

To use these new sensors:

1. In **HACS**, open the F1 integration.
2. Click the **three dots** (top right) → **Redownload**.
3. Check **"Show beta versions"** or **"Need a different version?"**.
4. Select this **pre-release** and download it.
5. Go to **Settings > Devices & Services**, find the F1 integration.
6. Click the **three dots** → **Reconfigure**, and enable the new sensors by checking the boxes.

---

### Known Issue

`sensor.f1_season_results` may trigger a warning in the Home Assistant logs:

```yaml
Logger: homeassistant.components.recorder.db_schema
Source: components/recorder/db_schema.py:663
Integration: Recorder
State attributes for sensor.f1_season_results exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
```

Despite the warning, the sensor should still work fine for display in the frontend. However, to avoid any database load/performance issues, it is recommended to **exclude this sensor from being recorded** in your `recorder:` config:

```yaml
recorder:
  exclude:
    entities:
      - sensor.f1_season_results
```

---

<hr /><em>This discussion was created from the release <a href='https://github.com/Nicxe/f1_sensor/releases/tag/v0.1.2'>v0.1.2</a>.</em>
